### ISSUE TITLE
[P0][CI-RED] GlobalHeader references undefined `isLoading` — header crashes via DashboardErrorBoundary, 3 auth-smoke E2E tests fail deterministically (regression from #1028)

### ISSUE THREAD

**Issue by SaifulHaqueNiloy** [SaifulHaqueNiloy/supremeai#1048]
## Summary

**Main CI is RED** — the `📋 QA Contract / 🎭 Playwright E2E Smoke Tests` job has failed on **15 consecutive main commits** since `049d43cc` (`fix(#972): frontend UX — 4 issues fixed (#1028)`), always the same 3 tests:

- `e2e/auth-smoke.spec.ts:157` — 401 on /auth/me invalidates the session (fail-closed)
- `e2e/auth-smoke.spec.ts:178` — logout clears the token and returns to login
- `e2e/auth-smoke.spec.ts:193` — relogin after logout works

Last green CI Pipeline on main: run `35603898275` @ `252409c5` (2026-09-21 13:10).

## Root cause (reproduced locally, deterministic — not flake)

`frontend/src/components/shell/GlobalHeader.tsx:161` (introduced by #1028):

```tsx
{isLoading ? 'CHECKING…' : isServerOnline ? 'SYSTEM OPERATIONAL' : 'SYSTEM UNAVAILABLE'}
```

`isLoading` is **not defined anywhere in the component**. `tsc` confirms:

```
src/components/shell/GlobalHeader.tsx(161,10): error TS2304: Cannot find name 'isLoading'.
```

The vite production build **does not type-check**, so the broken bundle ships. At runtime, evaluating the header render throws `ReferenceError: isLoading is not defined`, which the `DashboardErrorBoundary` catches and replaces the shell:

```
- heading "Dashboard Module Failure" [level=2]
- paragraph: A critical module in the admin dashboard has crashed. The rest of the system remains intact.
- generic: isLoading is not defined
- button "Reboot Dashboard Module"
```

This explains all 3 failures exactly:
1. **:178 / :193** — the Account menu button lives inside the crashed header region → `getByRole('button', { name: 'Account menu' })` never appears → 15s click timeout.
2. **:157** — after the /auth/me-401 reload, the error boundary replaces the router shell → ProtectedRoute never re-evaluates → no bounce to `/login` (token-poll assertion passes first).

## Aggravating factors

- The E2E job builds with `VITE_USE_RELATIVE_PATH=true` only — no type-check step runs before `playwright test`, so TS2304 never gates CI.
- Why #1028's PR checks passed: the change predates the current main-only E2E job ordering; PR pipeline for #1028 did not run this job (or ran against a merge-base without the file), and the 3 failing tests are the only ones that interact with the header.

## Additional findings during root analysis (same area)

- `useServerStream()` (the ONLY runtime writer of `isServerOnline` via `setServerStatus`) is **never mounted anywhere** — the hook's consumers are tests/comments only. In production `isServerOnline` stays at its store default (`false`), so the header label is permanently `SYSTEM UNAVAILABLE` once the crash is fixed. The "CHECKING…" loading UX intended by #972/#1028 was never wired to a real probe state.

## Proposed fix (minimal, root-cause)

1. Replace the undefined `isLoading` ternary with the last-green behavior (`{isServerOnline ? 'SYSTEM OPERATIONAL' : 'SYSTEM UNAVAILABLE'}`) — restores the header render.
2. Guard rail: run `tsc -b tsconfig.app.json --noEmit` locally pre-push (it already catches TS2304); consider a follow-up to add `tsc --noEmit` to the E2E/build job so a typed-but-unchecked regression cannot ship again.
3. Follow-up (separate issue, not this fix): either mount `useServerStream` at the App root and add a real `isServerStatusChecking` store flag to implement the #972 "CHECKING…" UX honestly, or drop the intent.

## Verification plan

- Local repro currently: `3 failed / 3 passed` on `e2e/auth-smoke.spec.ts` against `vite preview` (relative-path build). After fix: `6 passed`.
- Full auth-smoke suite + `tsc --noEmit` clean + targeted vitest for shell/header.

Closes the E2E failure class blocking every PR on main (incl. #1044).

**Comment by SaifulHaqueNiloy** [comment]
✅ RESOLVED — root cause (PR #1028 introduced undefined `isLoading` in GlobalHeader.tsx:161) fixed by #1055 (merged, main `5187f709`); server-health wiring followed in #1056. Playwright E2E smoke: SUCCESS on current main. Auto-close.
