### ISSUE TITLE
[P0][CI-RED] GlobalHeader references undefined `isLoading` — header crashes via DashboardErrorBoundary, 3 auth-smoke E2E tests fail deterministically (regression from #1028)

### ISSUE THREAD

**Issue by SaifulHaqueNiloy** [SaifulHaqueNiloy/supremeai#1052]
## Summary

**Main CI Pipeline has been RED since `252409c5` (run 35603898275, 2026-09-21 13:10)** — 15+ consecutive failing commits, all failing the same 3 Playwright auth-smoke tests:

- `e2e/auth-smoke.spec.ts:157` — 401 on /auth/me invalidates the session (fail-closed)
- `e2e/auth-smoke.spec.ts:178` — logout clears the token and returns to login
- `e2e/auth-smoke.spec.ts:193` — relogin after logout works

## Root cause (reproduced locally — deterministic, not flake)

`frontend/src/components/shell/GlobalHeader.tsx:161`, introduced by #1028 (fix #972):

```tsx
{isLoading ? 'CHECKING…' : isServerOnline ? 'SYSTEM OPERATIONAL' : 'SYSTEM UNAVAILABLE'}
```

`isLoading` is **not defined** in the component (`tsc`: `TS2304: Cannot find name 'isLoading'`). The vite production build **does not type-check**, so the broken bundle shipped. At runtime the header render throws `ReferenceError: isLoading is not defined`, caught by `DashboardErrorBoundary`, which replaces the shell:

```
- heading "Dashboard Module Failure" [level=2]
- generic: isLoading is not defined
- button "Reboot Dashboard Module"
```

Failure mapping:
1. **:178 / :193** — Account menu button lives inside the crashed header region → `getByRole('button', { name: 'Account menu' })` never appears → 15s click timeout (across all 3 CI retries).
2. **:157** — after the /auth/me-401 reload the boundary replaces the router shell → ProtectedRoute never re-evaluates → no `/login` bounce (the token-poll assertion passes first).

## Deeper finding

`useServerStream()` — the ONLY runtime writer of `isServerOnline` — is **never mounted anywhere** (consumers: tests + comments only), and the store has no "checking" flag. The #972 "CHECKING…" UX was never real; #1028 faked it with an undefined variable.

## Fix

1. Remove the undefined `isLoading` ternary (restore last-green binary label).
2. Wire a REAL `isServerStatusChecking` store flag + mount `useServerStream` at the App root (follow-up patch, #1053).
3. Prevention: PR-Helper type-gate so a typed-but-unchecked TS2304 cannot ship again (#1054).

## Verification (local, no CI)

- Before: auth-smoke `3 failed / 3 passed` (matches CI exactly).
- After fix: **6/6 passed**; full E2E suite **26/26 passed**; `tsc --noEmit` clean for the touched file.
